apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    name: postgres-service
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: postgres-port
      protocol: TCP
      port: 5432
      targetPort: 5432
