apiVersion: v1
kind: Service
metadata:
  name: prisma-studio-service
  labels:
    name: prisma-studio-service
spec:
  type: NodePort
  selector:
    app: prisma-studio
  ports:
    - name: prisma-studio-port
      protocol: TCP
      port: 5555
      targetPort: 5555
      nodePort: 31555
