apiVersion: v1
kind: Service
metadata:
  name: api-tech-challenge-service
  labels:
    name: api-tech-challenge-service
spec:
  type: NodePort
  selector:
    app: api-tech-challenge
  ports:
    - name: api-port
      protocol: TCP
      port: 3333
      targetPort: 3333
      nodePort: 30007
