name: 'CI - Infrastructure'

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Run Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.1.7'

      - name: Configure AWS credencials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform init EKS
        run: |
          terraform init

      - name: Terraform Validate EKS
        run: |
          terraform validate

      - name: Terraform Plan EKS
        id: terraform-plan
        run: |
          terraform plan -var="account_id_voclabs=${{ vars.AWS_ACCOUNT_KEY }}" -var="project_name=${{ vars.PROJECT_NAME }}" -var="region_default=${{ vars.AWS_REGION }}" -var="admin_user_email=${{ vars.COGNITO_ADMIN_USER_EMAIL }}" -var="admin_user_password=${{ secrets.COGNITO_ADMIN_USER_PASSWORD }}"

      - name: Terraform Apply EKS
        id: terraform-apply
        run: |
          terraform apply -auto-approve -var="account_id_voclabs=${{ vars.AWS_ACCOUNT_KEY }}" -var="project_name=${{ vars.PROJECT_NAME }}" -var="region_default=${{ vars.AWS_REGION }}" -var="admin_user_email=${{ vars.COGNITO_ADMIN_USER_EMAIL }}" -var="admin_user_password=${{ secrets.COGNITO_ADMIN_USER_PASSWORD }}"
