name: 'Terraform Workflow'

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Run Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.1.7'

      - name: Configure AWS credencials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ vars.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ vars.AWS_SESSION_TOKEN }}"
          aws-region: 'us-east-1'

      - name: Terraform init S3
        working-directory: s3
        run: |
          terraform init \
            -backend-config="region=${{ inputs.aws-region }}"

      - name: Terraform Validate S3
        working-directory: s3
        run: terraform validate

      - name: Terraform Plan S3
        working-directory: s3
        id: terraform-plan-s3
        run: |
          terraform plan

      - name: Terraform Apply S3
        working-directory: s3
        id: terraform-apply-s3
        run: |
          terraform apply

      - name: Terraform init EKS
        working-directory: eks
        run: |
          terraform init \
            -backend-config="region=${{ inputs.aws-region }}"

      - name: Terraform Validate EKS
        working-directory: eks
        run: terraform validate

      - name: Terraform Plan EKS
        working-directory: eks
        id: terraform-plan-eks
        run: |
          terraform plan -var="account_id_voclabs=${{ vars.AWS_ACCOUNT_KEY }}"

      - name: Terraform Apply EKS
        working-directory: eks
        id: terraform-apply-eks
        run: |
          terraform apply -auto-approve -var="account_id_voclabs=${{ vars.AWS_ACCOUNT_KEY }}"
