name: 'Dev Deploy'

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yaml
    with:
      environment: production
      aws-region: 'us-east-1'
